const products=[{id:1,name:'Paracetamol',detail:'Comprimidos · exemplo de catálogo',category:'Medicamento'},{id:2,name:'Dipirona',detail:'Comprimidos · exemplo de catálogo',category:'Medicamento'},{id:3,name:'Soro fisiológico',detail:'Solução · exemplo de catálogo',category:'Cuidados diários'},{id:4,name:'Gaze estéril',detail:'Pacote · exemplo de catálogo',category:'Primeiros cuidados'},{id:5,name:'Esparadrapo',detail:'Rolo · exemplo de catálogo',category:'Primeiros cuidados'},{id:6,name:'Algodão',detail:'Pacote · exemplo de catálogo',category:'Cuidados diários'}];
const cart=new Map();const $=s=>document.querySelector(s);let toastTimer;const total=()=>[...cart.values()].reduce((a,b)=>a+b,0);const lines=()=>[...cart].map(([id,q])=>`${q} × ${products.find(p=>p.id===id).name}`).join('\n');
$('#products').innerHTML=products.map(p=>`<article class="product"><div class="product-top"><span class="category">${p.category}</span><span class="number">0${p.id}</span></div><div class="product-body"><h3>${p.name}</h3><p>${p.detail}</p><button class="add" data-add="${p.id}" aria-label="Solicitar produto: ${p.name}">Solicitar produto <span>+</span></button></div></article>`).join('');
function render(){const n=total();$('#count').textContent=n;$('#openCart').setAttribute('aria-label',`Minha solicitação, ${n} produtos`);$('#checkout').disabled=!n;$('#cartSummary').textContent=n?`${n} unidade${n===1?'':'s'} na sua solicitação`:'Escolha produtos na vitrine para começar.';$('#cartItems').innerHTML=cart.size?[...cart].map(([id,q])=>{const p=products.find(p=>p.id===id);return `<div class="cart-row"><div><strong>${p.name}</strong><small>${p.category}</small></div><div class="qty"><button data-delta="-1" data-id="${id}" aria-label="Remover uma unidade de ${p.name}">−</button><span>${q}</span><button data-delta="1" data-id="${id}" aria-label="Adicionar uma unidade de ${p.name}" ${q>=99?'disabled':''}>+</button></div></div>`}).join(''):'<p>Sua lista ainda está vazia.</p>';}
function add(id){if(!products.some(p=>p.id===id))throw Error('Produto inválido');cart.set(id,Math.min(99,(cart.get(id)||0)+1));render();$('#toast').textContent='Produto adicionado à sua solicitação';$('#toast').style.display='block';clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').style.display='none',2200);return {units:total()};}
$('#products').addEventListener('click',e=>{const b=e.target.closest('[data-add]');if(b)add(Number(b.dataset.add));});
function openCart(){render();$('#cartDialog').showModal();}$('#openCart').onclick=openCart;$('#review').onclick=openCart;
$('#cartItems').addEventListener('click',e=>{const b=e.target.closest('[data-delta]');if(!b)return;const id=+b.dataset.id,q=(cart.get(id)||0)+Number(b.dataset.delta);if(q<=0)cart.delete(id);else cart.set(id,Math.min(99,q));render();});
document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());
$('#checkout').onclick=()=>{if(!cart.size)return;$('#cartDialog').close();$('#orderSummary').textContent=lines();$('#formDialog').showModal();};
$('#requestForm').onsubmit=e=>{e.preventDefault();const name=$('#name').value.trim(),phone=$('#phone').value.replace(/\D/g,'');if(name.length<2){$('#name').setCustomValidity('Informe seu nome.');$('#name').reportValidity();return;}if(phone.length<10||phone.length>13){$('#phone').setCustomValidity('Informe um telefone com DDD.');$('#phone').reportValidity();return;}if(!cart.size)return;const answer=new FormData(e.target).get('prescription');$('#successSummary').textContent=`${lines()}\n\nNome: ${name}\nTelefone: ${$('#phone').value}\nPossui receita: ${answer}`;$('#formDialog').close();$('#successDialog').showModal();cart.clear();render();e.target.reset();};
['name','phone'].forEach(id=>$('#'+id).oninput=()=>$('#'+id).setCustomValidity(''));$('#successDialog').addEventListener('close',()=>$('#successSummary').textContent='');render();
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'read_product_catalog',description:'Lista os produtos demonstrativos e a solicitação atual.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({products,cart:[...cart].map(([id,quantity])=>({id,quantity}))})})).catch(()=>{});Promise.resolve(document.modelContext.registerTool({name:'add_product_to_request',description:'Adiciona um produto à lista demonstrativa; não envia pedido.',inputSchema:{type:'object',properties:{id:{type:'integer',minimum:1,maximum:6}},required:['id'],additionalProperties:false},annotations:{readOnlyHint:false},execute:input=>{if(!input||!Number.isInteger(input.id))throw Error('ID inválido');return add(input.id);}})).catch(()=>{});}catch{}}
